# Copyright 2016 byteslounge.com (Gonçalo Marques).
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

sudo: required
services:
  - docker
language: scala
script: >
  sbt compile &&
  sbt "project mysql" docker &&
  sbt "project oracle" docker &&
  sbt "project postgres" docker &&
  sbt "project mysql" dockerComposeUp &&
  sbt test &&
  sbt alldbs:test &&
  sbt "project mysql" dockerComposeStop &&
  sbt "project db2" docker &&
  sbt "project db2" dockerComposeUp &&
  sbt db2:test &&
  sbt "project db2" dockerComposeStop
after_success:
- sbt coverageReport coveralls
env:
  global:
    secure: "FEMOF8BzuqL5oEIHHh/FP4u2XDWmJEhGN9Z6LLHbRYfp1o0DrSXsscO1FnwuzYg4yj9iYiWVYChRyy7feXBLmb/Zk94579fLyaFMD+3/vQr9dTk0WhEWr5/g7SuUYyAd4d+2ir73NddDW3umzjPmmVptBK3cPdF3p9qrpzXWgyavjdGsrdcxhfNALEkBGY04pptLUczoFB5coQRhwp0yyeVzjJQrn57NEfSVKq5tMpkYJLCQoUPOoLB6h2PTqahmfi8JE9cqhExl31lkRn72hFhF34VvcXEyBZtrKQsrqmnwFoFPWZ8PKGPai+5wPConAQvM3FFiJrCfYrIgxc53QdZ+e62wnnsPYfuXzqtCURtw6GQy7mTOxq7U1MvoTETqdo31S9wRIKW++Z0kzemV3jd13tS0UxWG0BIyE97mufow+6HcvwZ4YZ8j9qnjBotmhKyCbbrb0o7c81WOw8u0s0qyzVRz7Mg0B2RaMbmz2riVyNIBXeUte/ucgQC5HUQm+jIMgO13wkZ7vHPjuaqjH7KO/o1X2l09ws35WtmqM8hhJu5dEF+3eG1m/gHZAvvfzxOTNDAOLI0Agdp8DJzTnXGO1TPJ4WyvTss8fE2N8hkdfoTEJ6YWDy1klGq8sEatK9prfoz/RKWB8+cK0+C+VzTkAKdZvKdB4oyP74/pqfE="
